### PR TITLE
[UnityBuild?] Fix compilation error due to missing parallel utils include 

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
Current master fails to compile for me for the PotentialFlow and ShapeOptApp due to missing includes.

After doing git bisect I have seen it is due to this change:

https://github.com/KratosMultiphysics/Kratos/commit/f26f571ebcc3f0e793f3cbfdf17ac227b6d82836

which I guess was doing the include of parallel_utilities implicitly for the utilities in this PR.

This was for some reason not detected by the non-unity CI. Any clue why? @philbucher 

**Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Add missing include in potential flow app
- Add missing include in shape opt app

### CODE REVIEW

**Review by armingeiser — APPROVED** [review]

**Review by inigolcanalejo — APPROVED** [review]

**Comment by philbucher** [comment]
the non-unity CI contains only the core as it is much slower
