### PR TITLE
Fixing compilation error and linking error after pybind port

### PR DESCRIPTION
**Pull request by ipouplana**
I just tried to compile the master branch after the merge of the pybind port and I found a linking error in Dam Application. I repaired it just by linking Dam to both SolidMechanics and Poromechanics Apps.

I also found some compilation errors in some utilities that weren't including the modelpart.

With these changes I managed to compile properly, but please @joaquinirazabal try to run some of your tests to see if everything works as expected.

### CODE REVIEW

**Review by joaquinirazabal — APPROVED** [review]
Great job! Everything is working!
