### ISSUE TITLE
Compilation error -> certain apps with the most recent master version

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#8176]
**Description**
Problem compiling

- FreeSurfaceApplication 
- ShallowWaterApplication @KratosMultiphysics/shallow-water 
- PfemFluidDynamicsApplication @KratosMultiphysics/pfem 
- DelaunayMeshingApplication

with the most recent master on Ubuntu18. Any similar experience? Other apps (fluid dynamics, structural mechanics, rans, trilinos) have no issues.

**Comment by philbucher** [comment]
this is caused by #7381 which was merged today
I am guessing the corresponding developers will address this soon

sorry for the inconvenience, this change was announced for years, details see #7381 :/

**Comment by miguelmaso** [comment]
Thanks for reporting. I'm checking ShallowWaterApplication, it was compiling without warnings

**Comment by miguelmaso** [comment]
shallow water app is fixed

**Comment by maceligueta** [comment]
Just tagging @AFranci , in case he is not aware of these problems.

**Comment by AFranci** [comment]
Hi all and thank you for reporting.
I'm sorry for the inconvenience, but these days I'm very busy and I will not be able to take a look at this before the next week.

**Comment by AlejandroCornejo** [comment]
Solving for pfem, Delaunay and FEMtoDEM here: https://github.com/KratosMultiphysics/Kratos/pull/8199

**Comment by AlejandroCornejo** [comment]
- PfemFluidDynamicsApplication @KratosMultiphysics/pfem

- DelaunayMeshingApplication

SOLVED

**Comment by RiccardoRossi** [comment]
can the issue be closed then?

**Comment by AlejandroCornejo** [comment]
seems that `FreeSurfaceApplication` is remaining

**Comment by mpentek** [comment]
Thanks!
