### PR TITLE
Trying to fix compilation error.

### PR DESCRIPTION
**Pull request by jcotela**
I'm altering an operation that did not compile in gcc 7.2.0. Apparently the issue is that std::abs is not defined for unsigned types and should fail if you try to use it (std::abs makes no sense for an unsigned int, "negative numbers" are very large unsigned integers). I've tried to fix the error while respecting the spirit of the original code, but feel free to use a different solution instead.

### CODE REVIEW

**Review by msandre — APPROVED** [review]
I'm ok with the modifications. We could even comment the entire for loop out. I had added this check at the time to be 100% sure the node ordering didn't change. But it should always be sorted. I think after we have the hdf5 app this code should not be needed anymore so I would just leave the fix for now so the compiler doesnt complain.
