### ISSUE TITLE
Compilation error on Centos 7

### ISSUE THREAD

**Issue by mohittyagi-k** [KratosMultiphysics/Kratos#8257]
**Description**

Getting the following error on centos7 for `ExecuteFunctorInContainer` 

![image](https://user-images.githubusercontent.com/62013692/107359318-8c1cd480-6afa-11eb-9646-ac4241894441.png)

**Scope**
This is happening during compilation on centos7 (GNU 4.8.5). Compiles fine with GNU 8.3.1 or MSVC.

Resolution of the issue required for the latest merge of Kratos.

Attn: @sunethwarna @ddiezrod @pooyan-dadvand @KratosMultiphysics/altair

**Comment by pooyan-dadvand** [comment]
Maybe related:
https://stackoverflow.com/questions/20006574/workaround-for-variadic-lambda-capture

**Comment by sunethwarna** [comment]
I'm sorry I'm little bit lost in here, I don't have any way to reproduce or test this :/

**Comment by philbucher** [comment]
@KratosMultiphysics/altair why don't you add your configuration to the CI?
I saw the other day that CentOS [offers docker containers](https://hub.docker.com/_/centos) (same as e.g. Ubuntu does). There are also [other resources](https://github.com/precice/ci-images/blob/master/ci-centos7.dockerfile) that can be interesting.

Having set up several times already the CI with Github actions I am quite sure you can do this within one day (You basically can copy paste what we have already for the other OSs), at least for the compilation Core which would be a huge help already. I am guessing this is less time than you spend for fixing sth on master when merging it. I would be happy to help you!

Note that newer OSs don't even offer such old compilers in their package repos any more. Hence for others it is difficult to replicate the problems you have. And trying to fix such problems without any way to reproduce is quite frustrating as @sunethwarna points out

**Comment by ddiezrod** [comment]
That'd be really great. We are actually working on that on our side now. I dont completely understand how they work yet, so we may need some help from your side...

**Comment by philbucher** [comment]
> That'd be really great. We are actually working on that on our side now. I dont completely understand how they work yet, so we may need some help from your side...

sure, let me know as soon as you have a branch or PR, then I can take a look

**Comment by philbucher** [comment]
After speaking with @pooyan-dadvand and @sunethwarna we decided to try to remove some variadic templates which will hopefully solve the problem
