### ISSUE TITLE
[CI/Trilinos] CI fails due to timeout in Trilinos MPI tests

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#8418]
**Description**
The CI was failing in different compilers at different times due to timeout in running `TrilinosApplication` mpi tests. (Eg: in the PR #8141). I have put the same PR for a re-run (I merged the master again just to be sure).

It also fails now in Windows compilation. (Earlier it was only timeout failure on the above mentioned tests)

The windows error msg:
```
fatal error C1002: compiler is out of heap space in pass 2 [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore_unity.vcxproj]
2021-03-03T14:56:53.6878070Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\list(1096): fatal error C1002: compiler is out of heap space in pass 2
```

**Scope**
- CI
- MPI
- Testing

**To Reproduce**
In CI [ PR #8141 ]

**Expected behavior**
`TrilinosApplication` tests in mpi fails due to timeout

**Environment**
- OS: Manjaro KDE
- Branch: master
- Python 3.9.1

**Comment by sunethwarna** [comment]
@rubenzorrilla @mrhashemi may be you guys have an idea?

**Comment by philbucher** [comment]
I am pretty sure this is caused by #7896

**Comment by rubenzorrilla** [comment]
> I am pretty sure this is caused by #7896

Most probably yes, but we didn't add new tests in that PR. I can understand how we get out of time. About the heap space of the Windows compilation, I've no clue.

**Comment by philbucher** [comment]
> Most probably yes, but we didn't add new tests in that PR

you did!
https://github.com/KratosMultiphysics/Kratos/pull/7896/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.py#diff-5a3a46bd0060745436199d2785b66037492f8fed8594780378d25f8fabc9ecc2R121-R221

**Comment by rubenzorrilla** [comment]
> > Most probably yes, but we didn't add new tests in that PR
> 
> you did!
> https://github.com/KratosMultiphysics/Kratos/pull/7896/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.py#diff-5a3a46bd0060745436199d2785b66037492f8fed8594780378d25f8fabc9ecc2R121-R221

True. Same test but with different settings. Sorry...

**Comment by rubenzorrilla** [comment]
@mrhashemi would reduce the number of steps run in the test in a future PR. In the meantime lets move the long tests to the nightly suite.

**Comment by philbucher** [comment]
Fixed
