### PR TITLE
[pfem2] Fixing global ptr vector

### PR DESCRIPTION
**Pull request by miguelmaso**
#4851 after changes in the global pointer vector, there was still some compilation errors

### CODE REVIEW

File: applications/pfem_2_application/custom_utilities/move_particle_utility_pfem2.h [hunk 1]
```diff
@@ -2742,7 +2743,7 @@ namespace Kratos
 				bool is_found_2 = CalculatePosition(geom,coords[0],coords[1],coords[2],N);
 				if (is_found_2)
 				{
-					pelement=neighb_elems(i).lock();
+					pelement = neighb_elems[i].shared_from_this();
```
Comment (philbucher) [inline applications/pfem_2_application/custom_utilities/move_particle_utility_pfem2.h:2746]: @RiccardoRossi shouldn't there be a better solution to this?

I mean to make it work again it is ok, but to me it seems like alos some things should be rewrtitten to use intrusive_ptr (or even raw ptrs) instead of shared_ptr in the elements right?
Ther the `shared_from_this` would not be needed I think

**Review by philbucher — APPROVED** [review]

**Comment by miguelmaso** [comment]
thanks @philbucher

**Comment by miguelmaso** [comment]
broken after #4835
