### PR TITLE
[CI] activating centos7 compilation in CI

### LINKED ISSUE #8257: Compilation error on Centos 7
**Description**

Getting the following error on centos7 for `ExecuteFunctorInContainer` 

image

**Scope**
This is happening during compilation on centos7 (GNU 4.8.5). Compiles fine with GNU 8.3.1 or MSVC.

Resolution of the issue required for the latest merge of Kratos.

Attn: @sunethwarna @ddiezrod @pooyan-dadvand @KratosMultiphysics/altair

### PR DESCRIPTION
**Pull request by ddiezrod**
Just that. We should see here the issue mentioned in #8257

### CODE REVIEW

**Comment by ddiezrod** [comment]
: / Still seems that it is not able to find the image.

**Comment by philbucher** [comment]
you need to wait until the image is built (which happened AFTER you merged the other PR)
This PR was opened ~10min before the image was uploaded
It is there: https://hub.docker.com/r/kratosmultiphysics/kratos-image-ci-centos7-python35

**Comment by philbucher** [comment]
now it found it
But the compilation doesn't work, but this you need to take a look at yourself.

**Comment by philbucher** [comment]
BTW I might have messed up sth here: https://github.com/KratosMultiphysics/Kratos/commit/a81e6bc4f29d384d1e6ef93c0075a3f41df8697f

**Comment by philbucher** [comment]
seems like you haven't installed boost in the container

**Comment by ddiezrod** [comment]
> seems like you haven't installed boost in the container

hmm yes, but shouldnt it take it from external_libraries/boost?

**Comment by philbucher** [comment]
> > seems like you haven't installed boost in the container
> 
> hmm yes, but shouldnt it take it from external_libraries/boost?

That doesn’t exist ...?
Or what do you mean?

**Comment by ddiezrod** [comment]
> > > seems like you haven't installed boost in the container
> > 
> > 
> > hmm yes, but shouldnt it take it from external_libraries/boost?
> 
> That doesn’t exist ...?
> Or what do you mean?

Upss, sorry I had a boost inside my external_libraries so I thought it was also there here. Nevermind, I think it should work now. Will  I need to deactivate CI again and open another MR?

**Comment by philbucher** [comment]
I would merge the changes to the docker in a separate PR and leave this one unmodified
Or you revert here the CI changes 

actually you could also leave the CI changes here since it is not a required check but then it would show up in every other PR which usually confuses devs

my recommendation: separate PR

**Comment by ddiezrod** [comment]
Hurray! Centos is failing! :P @sunethwarna @mohittyagi-k Maybe you can try here the solution proposed by @pooyan-dadvand ?

**Comment by mohittyagi-k** [comment]
> 
> 
> Hurray! Centos is failing! :P @sunethwarna @mohittyagi-k Maybe you can try here the solution proposed by @pooyan-dadvand ?

Good luck @sunethwarna 😄

**Comment by sunethwarna** [comment]
I'll give it a try....

**Comment by RiccardoRossi** [comment]
I just want to comment that in my opinion we should consider this temporary.
We are now in 2021, so full 10years behind the c++11 standard. 
One of the blockers is having to support this version of centos which comes with gcc4.8.5, which does not even support properly the full c++11 standard. 
We need some solutions for this ...

**Comment by sunethwarna** [comment]
Now it fails at a different point :/

**Comment by philbucher** [comment]
the current failure should be easy to fix, it is a problem with older GCCs, esserntially you need to add another pair of `{}` (man is this compiler old :sweat_smile:)

**Comment by rubenzorrilla** [comment]
> I just want to comment that in my opinion we should consider this temporary.
> We are now in 2021, so full 10years behind the c++11 standard.
> One of the blockers is having to support this version of centos which comes with gcc4.8.5, which does not even support properly the full c++11 standard.
> We need some solutions for this ...

Another question is if this CI workflow is mandatory for merging. I'd say that it should be for the KratosCore as well as for applications that are used in the @KratosMultiphysics/altair side. However, I don't think we should constraint the daily workflow of developers that have nothing to do with these.

**Comment by philbucher** [comment]
> > I just want to comment that in my opinion we should consider this temporary.
> > We are now in 2021, so full 10years behind the c++11 standard.
> > One of the blockers is having to support this version of centos which comes with gcc4.8.5, which does not even support properly the full c++11 standard.
> > We need some solutions for this ...
> 
> Another question is if this CI workflow is mandatory for merging. I'd say that it should be for the KratosCore as well as for applications that are used in the @KratosMultiphysics/altair side. However, I don't think we should constraint the daily workflow of developers that have nothing to do with these.

fully agree
The configure for the centos should only contain a subset of apps (aka the ones used by @KratosMultiphysics/altair)

**Comment by ddiezrod** [comment]
@rubenzorrilla @philbucher Completely agree. Those would be:

- FluidDynamicsApp
- StructuralMechanicsApp
- MeshingApp
- MappingApp

**Comment by ddiezrod** [comment]
CI is passing now. We can maybe merge this and add the apps in a different PR.

**Comment by philbucher** [comment]
I will approve after you solved the conflicts (sorry we were working on sth else and I didn't think this would cause problems here...)

**Comment by ddiezrod** [comment]
> I will approve after you solved the conflicts (sorry we were working on sth else and I didn't think this would cause problems here...)

FIxed ;)

**Review by philbucher — APPROVED** [review]
ok cool

I want to point out few things:
- the CentOS build is not requred (yet?) but at least it runs now with every PR so we can get some experience with it
- it is up to @KratosMultiphysics/technical-committee to decide whether this should be required in the future or not
- lets add more apps (only the ones used by @KratosMultiphysics/altair in a followup PR (probably you also want to activate MPI?)

**Comment by ddiezrod** [comment]
@philbucher Just to add that only build is run now, Tests should be added too,
