### PR TITLE
[Core][Geometry] Allowing high order derivatives

### PR DESCRIPTION
**Pull request by tteschemacher**
Hi all,

I am adding here the possibility to add higher order derivatives to the shape function container, which is introduced in #5214 . This PR is related to the issue #4777.

Tests are coming in the following PRs, because those need geometries with high order shape functions.

Thanks!

### CODE REVIEW

**Review by loumalouomega — COMMENTED** [review]
OK from my side, does this add a lot of memory usage?

**Comment by tteschemacher** [comment]
Not really, the shape function containers are typically static for all existant geometries. Only for the new types those will be non-static. And it only adds one empty container to the shape function values container.

**Comment by loumalouomega** [comment]
Travis fails

**Comment by loumalouomega** [comment]
~~~
/home/travis/build/KratosMultiphysics/Kratos/kratos/geometries/geometry_shape_function_container.h:312:40: error: invalid use of non-static data member ‘Kratos::GeometryShapeFunctionContainer<TIntegrationMethodType>::mDefaultMethod’

         IntegrationMethod ThisMethod = mDefaultMethod)

                                        ^~~~~~~~~~~~~~

/home/travis/build/KratosMultiphysics/Kratos/kratos/geometries/geometry_shape_function_container.h:351:23: note: declared here

     IntegrationMethod mDefaultMethod;
~~~

**Comment by tteschemacher** [comment]
Thanks, I fixed it by removing the default value.

**Review by pooyan-dadvand — DISMISSED** [review]
👍

**Comment by tteschemacher** [comment]
Now that the other refactoring is done. Can you agree on this concept @oberbichler ?

If yes, @pooyan-dadvand could you approve again?

File: kratos/geometries/geometry_shape_function_container.h [hunk 1]
```diff
@@ -237,6 +304,28 @@ class GeometryShapeFunctionContainer
...
+        IndexType DerivativeOrderIndex,
+        IndexType DerivativeOrderRowIndex,
+        IndexType ShapeFunctionIndex,
+        IntegrationMethod ThisMethod)
+    {
+        if (DerivativeOrderIndex == 0)
+            return mShapeFunctionsValues[ThisMethod](IntegrationPointIndex, ShapeFunctionIndex);
+        if (DerivativeOrderIndex == 1)
+            return mShapeFunctionsLocalGradients[ThisMethod][IntegrationPointIndex](DerivativeOrderRowIndex, ShapeFunctionIndex);
+        if (DerivativeOrderIndex > 2)
```
Comment (oberbichler) [inline kratos/geometries/geometry_shape_function_container.h]: `> 1?`

**Comment by oberbichler** [comment]
I dont have a use case for this. The important thing is that it matches your needs.

File: kratos/geometries/geometry_shape_function_container.h (hunk 1 above)
Comment (tteschemacher) [reply kratos/geometries/geometry_shape_function_container.h]: thx

File: kratos/geometries/geometry_shape_function_container.h [hunk 2]
```diff
@@ -237,6 +304,28 @@ class GeometryShapeFunctionContainer
         return mShapeFunctionsLocalGradients[ThisMethod][IntegrationPointIndex];
     }
 
+    /*
+    * @brief access each item separateley.
+    * @param DerivativeOrderIndex defines the wanted order of the derivative
+    * @param DerivativeOrderRowIndex within each derivative the entries can
+    *        be accessed differently.
+    * @return the shape function or derivative value related to the input parameters.
```
Comment (RiccardoRossi) [inline kratos/geometries/geometry_shape_function_container.h:364]: could u put here an example of the intended use of this?

File: kratos/geometries/geometry_shape_function_container.h [hunk 3]
```diff
@@ -60,25 +60,38 @@ class GeometryShapeFunctionContainer
...
+    typedef std::array<ShapeFunctionsDerivativesIntegrationPointArrayType, IntegrationMethod::NumberOfIntegrationMethods>
+        ShapeFunctionsDerivativesContainerType;
 
     ///@}
     ///@name Life Cycle
     ///@{
 
+    /// Constructor for single integration point having the full containers
     GeometryShapeFunctionContainer(
         IntegrationMethod ThisDefaultMethod,
```
Comment (RiccardoRossi) [inline kratos/geometries/geometry_shape_function_container.h:96]: I see that you have one container for all of the integration points at once.

My idea was to have one different container per each integration point.

so that you could do something like

~~~
auto integraiton_point_data = all_integration_points_container.GetPoint( 5 )
array_1d<double,3> v = data.GetVector(derivative_order,  .... ) <-------> this is what you would use in the PR about o
double d = data.GetValue(derivative_order, component ......)
~~~

Comment (tteschemacher) [reply kratos/geometries/geometry_shape_function_container.h:96]: This is only piecewise possible. However, this is not backwards compatible. The herein posted solution is applicable for all kratos.

File: kratos/geometries/geometry_shape_function_container.h (hunk 2 above)
Comment (tteschemacher) [reply kratos/geometries/geometry_shape_function_container.h:364]: This is just one way to use this container

Comment (tteschemacher) [reply kratos/geometries/geometry_shape_function_container.h:364]: My suggested way will be:
const Matrix& ShapeFunctionDerivatives(IndexType Order, IndexType IntegrationPointIndex)
Possible for orders: 1-...
Due to backwards compatibility 0 is not possible

Comment (RiccardoRossi) [reply kratos/geometries/geometry_shape_function_container.h:364]: what i was asking is how the data is actually stored in the return matrix (essentially i am asking for a small documentation of how to use it in this text

File: kratos/geometries/geometry_shape_function_container.h (hunk 3 above)
Comment (RiccardoRossi) [reply kratos/geometries/geometry_shape_function_container.h:96]: ok

**Review by RiccardoRossi — COMMENTED** [review]
Pooyan is approving, and it is ok also for me (aside for a petition of documentation).

@philbucher @roigcarlo @rubenzorrilla if you don't have any complain i'll approve, (nevertheless please @tteschemacher  do add the docstring i asked for)

File: kratos/geometries/geometry_shape_function_container.h (hunk 2 above)
Comment (tteschemacher) [reply kratos/geometries/geometry_shape_function_container.h:364]: I'll add this function

**Comment by tteschemacher** [comment]
@RiccardoRossi I added now the interface which I meant.

I first wanted to do this in a further PR, anyways, now it is here. I would suggest that this interface will be used throughout the majority of functions. It would reduce also some other functions.

It postpones the discussion of the ordering a bit because it only provides the matrix.

In a further PR I will reduce all SecondOrderDerivativeFunctions and this stuff because this is then outdated.

**Comment by tteschemacher** [comment]
To my opinion this PR is now ready to be merged.

anyone further suggestions?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees about the interface but the order of derivatives for geometries with different dimensions and at least for the first two derivatives should be documented

**Review by philbucher — APPROVED** [review]

**Comment by tteschemacher** [comment]
thx
