### PR TITLE
Core/solve issues with old gcc

### PR DESCRIPTION
**Pull request by ddiezrod**
**Description**
This does not work in gcc 4.8 even in c++11  :(   ("official" compiler in centos7)

### CODE REVIEW

**Comment by roigcarlo** [comment]
Mm not blocking but delegating constructors should work since gcc 4.7

**Comment by philbucher** [comment]
I added the same in `ModelPart` over a year ago: #4976

**Comment by roigcarlo** [comment]
Maybe it because there are explicit

**Comment by ddiezrod** [comment]
I think @roigcarlo is right. The one in the model part compiles without any problem. @philbucher

**Comment by philbucher** [comment]
How abt adding explicit to thise ctors?
Does it work then?

**Comment by roigcarlo** [comment]
Could be the interaction of explicit, delegatings and being a templated class.
Maybe we could try to 

`explicit Scheme(Parameters ThisParameters) : Scheme<TSparseSpace, TDenseSpace>()` ?¿

**Comment by ddiezrod** [comment]
@philbucher the default constructors already have the explicit keyword.. I will try @roigcarlo 's suggestions

**Comment by roigcarlo** [comment]
Also if you could post the error @ddiezrod  :D I am making suggestions blindly

**Comment by ddiezrod** [comment]
/home/gitlab-runner/builds/TCRVYhAY/0/poesis/Poesis/kratos/kratos/solving_strategies/schemes/scheme.h:190:57: error: no matching function for call to ‘Kratos::Scheme<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >::Scheme()’
      explicit Scheme(Parameters ThisParameters) : Scheme()
                                                          ^

**Comment by ddiezrod** [comment]
same error Im afraid doing 

`explicit Scheme(Parameters ThisParameters) : Scheme<TSparseSpace, TDenseSpace>() 
`
 /home/gitlab-runner/builds/xkuP_8K-/0/poesis/Poesis/kratos/kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp:1006:1:   required from here
 /home/gitlab-runner/builds/xkuP_8K-/0/poesis/Poesis/kratos/kratos/solving_strategies/schemes/scheme.h:190:83: error: no matching function for call to ‘Kratos::Scheme<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >::Scheme()’
      explicit Scheme(Parameters ThisParameters) : Scheme<TSparseSpace,TDenseSpace>()

**Comment by ddiezrod** [comment]
Closed by mistake sorry

**Comment by roigcarlo** [comment]
Does the error have a list with "candidates are... Bla bla bla" with the individual errors or is just that?

**Comment by ddiezrod** [comment]
nop... no candidates im afraid
[output.txt](https://github.com/KratosMultiphysics/Kratos/files/4926667/output.txt)

**Comment by roigcarlo** [comment]
To be honest it eludes me, and I am not able to rerpduce it so if @philbucher agrees we can approve :/

**Comment by ddiezrod** [comment]
so.. can someone approve this then?

**Review by philbucher — APPROVED** [review]
:/

**Comment by ddiezrod** [comment]
Thanks @philbucher ,  I know, life is disappointing sometimes XD
