### PR TITLE
[MeshinApplication][Tetgen] Fixing compilation error

### PR DESCRIPTION
**Pull request by miguelmaso**
@juliobarna I think this will solve your problem
This was broken after #4835

### CODE REVIEW

**Comment by philbucher** [comment]
is this still active?

**Comment by miguelmaso** [comment]
@juliobarna can we close this?

**Comment by juliobarna** [comment]
Hola, si! Gracias
