### ISSUE TITLE
SimpleMortarMapperProcess fails Windows compilation

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#918]
I got this error recently when compiling Kratos on Windows

1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,4,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$03V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<3,3,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$02$02V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,1>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,1>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$00@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,1>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$00@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<class Kratos::array_1d<double,3> >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@V?$array_1d@N$02@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::VariableComponent<class Kratos::VectorComponentAdaptor<class Kratos::array_1d<double,3> > >,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$VariableComponent@V?$VectorComponentAdaptor@V?$array_1d@N$02@Kratos@@@Kratos@@@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,0>::ExecuteExplicitMapping(void)" (?ExecuteExplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)
1>add_processes_to_python.obj : error LNK2019: unresolved external symbol "private: void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,0>::ExecuteImplicitMapping(void)" (?ExecuteImplicitMapping@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$0A@@Kratos@@AEAAXXZ) referenced in function "public: virtual void __cdecl Kratos::SimpleMortarMapperProcess<2,2,class Kratos::Variable<double>,0>::Execute(void)" (?Execute@?$SimpleMortarMapperProcess@$01$01V?$Variable@N@Kratos@@$0A@@Kratos@@UEAAXXZ)

@roigcarlo do you also have the same problem?

**Comment by loumalouomega** [comment]
To many templates

**Comment by roigcarlo** [comment]
Hi @vryy, Looks like a visibility problem, probably introduced in #839. I havn't try to compile that code in windows yet, I'll check that tomorror. 
@loumalouomega Is the SimpleMortarMapperProcess class exported?

**Comment by loumalouomega** [comment]
exported?

**Comment by roigcarlo** [comment]
KRATOS_API(APPLICATION_NAME)

**Comment by loumalouomega** [comment]
Is in the core

**Comment by roigcarlo** [comment]
I see, but if they are used in any other app they need to be exported with KRATOS_API(KRATOS_CORE). I don't have any windoes machine ready now, we can check it tomorrow morning

**Comment by loumalouomega** [comment]
Ok, but is added directly to python, not imported in any application

**Comment by roigcarlo** [comment]
I think the problem is that `simple_mortar_mapper_process.cpp` is in KRATOS_CORE
while the interface `add_processes_to_python.cpp` to it is in KRATOS

There are two different libs so KRATOS cannot find the symbols in KRATOS_CORE ( in win ).

But as I said its very easy to fix, we can do it tomorrow in 5 min.

**Comment by roigcarlo** [comment]
@vryy We identified the error and it is solved. Once we finish to compile the project to check the changes we will make the PR.

**Comment by loumalouomega** [comment]
Hurray
