### PR TITLE
Many 'override' added to the kratos core.

### PR DESCRIPTION
**Pull request by maceligueta**

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
Have you ran the tests?

**Comment by maceligueta** [comment]
@pooyan-dadvand : yes. I don't see new errors in this branch. The result of the tests is the same as in Master Branch: 
Master:          .EEE.............E......s.......E....s.s   FAILED (errors=6, skipped=3, expected failures=3)
This branch:  .EEE.............E......s.......E....s.s    FAILED (errors=6, skipped=3, expected failures=3)

**Comment by maceligueta** [comment]
It looks like the method 'assertRaisesRegex' had a different name in Python<3.2, its old name was 'assertRaisesRegexp'

**Comment by maceligueta** [comment]
I commited some changes to improve compatibility with Python <3.2. Unfortunately, these changes are in this branch, not in a separate one (sorry).

**Comment by maceligueta** [comment]
I am still gettin one error in the tests (master branch!):
```
======================================================================
ERROR: test_amgcl_bicgstabl (test_linear_solvers.TestLinearSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maceli/kratos/kratos/tests/test_linear_solvers.py", line 341, in test_amgcl_bicgstabl
    """)
  File "/home/maceli/kratos/kratos/tests/test_linear_solvers.py", line 17, in _RunParametrized
    self._auxiliary_test_function(settings)
  File "/home/maceli/kratos/kratos/tests/test_linear_solvers.py", line 47, in _auxiliary_test_function
    linear_solver.Solve(A,x,b)
RuntimeError: Zero rho in BiCGStab(L)
```
Can anyone reproduce it? Or is it just me?

**Comment by jcotela** [comment]
I'm not getting errors on the test you mention. For me the core tests run with 1 expected failure, 3 skips. (by the way, the default test script fails on my machine because I don't have a runkratos, but it works fine if I just hack the test script to spawn processes with `python` instead of `some_path/runkratos`).

**Comment by maceligueta** [comment]
@RiccardoRossi  just told me (by phone) that this error appears just sometimes. He suspects it might depend on the compiler, but nobody found the source of the problem yet. Anyway, it is not a problem introduced in this branch, as it is present in the master branch already.

File: kratos/tests/test_model_part_io.py [hunk 1]
```diff
@@ -4,13 +4,18 @@
...
 
 def GetFilePath(fileName):
     return os.path.dirname(os.path.realpath(__file__)) + "/" + fileName
 
 
 class TestModelPartIO(KratosUnittest.TestCase):
+    
+    def setUp(self):        
+        if (sys.version_info < (3, 2)):
+            self.assertRaisesRegex = self.assertRaisesRegexp
```
Comment (RiccardoRossi) [inline kratos/tests/test_model_part_io.py:18]: @roigcarlo, can't we change this in the base class of the KratosUnitTest?

**Review by RiccardoRossi — APPROVED** [review]
I think this is a change for good. on my side i would approve the merging of this. All the tests pass on my computer

i just added a comment for @roigcarlo since there might be a cleaner solution for the regex changes you propose. Not a blocker though...

File: kratos/tests/test_model_part_io.py (hunk 1 above)
Comment (roigcarlo) [reply kratos/tests/test_model_part_io.py:18]: The problem is that as @maceligueta says it is a different call. What I can do is to hide it behind the KratosUnittest class. Would that help?

Comment (RiccardoRossi) [reply kratos/tests/test_model_part_io.py:18]: if we could hide it so that it works the same on python2.7 and python3+ it would be better, since we would avoid user-side ifs.

is that very complicated?

Comment (roigcarlo) [reply kratos/tests/test_model_part_io.py:18]: Give me a sec and I'll make a commit

File: kratos/spatial_containers/bounding_volume_tree.h [hunk 2]
```diff
@@ -270,11 +270,11 @@ class _6DOP : public kDOP // AABB
     KRATOS_CLASS_POINTER_DEFINITION(_6DOP);
     _6DOP() : kDOP() {this->Initialize();}
     virtual ~_6DOP() {}
-    virtual std::size_t NumberOfDirections() const {return 3;}
+    virtual std::size_t NumberOfDirections() const override {return 3;}
 
 private:
     static const double msDirection[][3];
-    virtual const double (*Direction() const)[3];
+    virtual const double (*Direction() const override)[3];
```
Comment (roigcarlo) [inline kratos/spatial_containers/bounding_volume_tree.h]: This does not compile in my machine (clang 3.9) and it still complains about the warning it tries to solve.

My guess is that there is something strange with the (***)[3]. I am not familiar with that syntax, may I ask which is the purpose of the array at the end?

Same with the others ```(*Direction() const override)[3];```

The error:
```
/home/roigcarlo/Kratos/kratos/spatial_containers/bounding_volume_tree.h:277:46: error: expected ')'
    virtual const double (*Direction() const override)[3];
                                             ^
/home/roigcarlo/Kratos/kratos/spatial_containers/bounding_volume_tree.h:277:26: note: to match this '('
    virtual const double (*Direction() const override)[3];
                         ^
/home/roigcarlo/Kratos/kratos/spatial_containers/bounding_volume_tree.h:277:28: warning: 'Direction' overrides a member function but is not
      marked 'override' [-Winconsistent-missing-override]
    virtual const double (*Direction() const override)[3];
                           ^
/home/roigcarlo/Kratos/kratos/spatial_containers/bounding_volume_tree.h:253:28: note: overridden virtual function is here
    virtual const double (*Direction() const)[3];
```

Comment (RiccardoRossi) [reply kratos/spatial_containers/bounding_volume_tree.h]: i also do not understand the syntax...

Comment (maceligueta) [reply kratos/spatial_containers/bounding_volume_tree.h]: I hope @pooyan-dadvand will help us on this. I just put 'override' everywhere gcc was recommending it (the flag -Wsuggest-override).

Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: Still not sure what it does but ```(*Direction() const)[3] override;``` seems to solve the problem

Comment (maceligueta) [reply kratos/spatial_containers/bounding_volume_tree.h]: This did not compile with my gcc when I tried... Did you try it with gcc?

Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: Still compiling the Clang version, when it does I'll try with gcc

Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: It fails with gcc, I also can confirm that the original code works with gcc. It terrifies me what will happen with MSVC...

Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: We've been looking at this with @jcotela and the conclusion is that the line tries to return a `variable[][3]`. Since it seems to be returned by reference and for every implementation the size of the first array is different, it return its as a pointer. In other words it wants to return ```(*)[3]``` but this is syntactically incorrect.

Somehow the construction:
```C++
type (*Function() const)[x]
```

Works, but I personally suspects that this is an abuse of the notation and it was not taken into account while extending the parser for C++ decorators.

If one defines 

```C++
typedef const double BaseType[3];
typedef BaseType* ArrayType;
```

Then the code can be rewritten as:

```C++
# Header
virtual kDOP::ArrayType Direction() const override;

# Impl
kDOP::ArrayType _6DOP::Direction() const {return msDirection;}
```

Not 100% sure that it does the same but this way it compiles and can have the ```override``` decorator.

Anyone can try this out?

Comment (pooyan-dadvand) [reply kratos/spatial_containers/bounding_volume_tree.h]: Dear @vryy would you please take look to this modification?

**Comment by RiccardoRossi** [comment]
just to tell that if one has clang than the overrides can be added automatically by doing

python /home/rrossi/compiled_libraries/clang-39/share/clang/run-clang-tidy.py -checks=-*,modernize-use-override -fix

(PATH should be modified so that clang-tidy can be found)

HOWEVER clang-tidy currently chokes on the function that Carlos identified

File: kratos/spatial_containers/bounding_volume_tree.h (hunk 2 above)
Comment (vryy) [reply kratos/spatial_containers/bounding_volume_tree.h]: @roigcarlo, you are correct, virtual const double (*Direction() const)[3]; returns a set of direction vectors associated with a kDOP under the form of a 2D array. Those vectors are static so I kept an internal static array and give a function to return a pointer to it. Technically returns a const pointer to the first array of the 2D array.

The original code does not have override and it was compiled fine with gcc. But I can try your suggestion to remove the annoying of other compilers.

@pooyan-dadvand i'll take some time to check this

**Comment by maceligueta** [comment]
Does anyone know if the conflict should be resolved with 3.0 or 6.0?

File: kratos/spatial_containers/bounding_volume_tree.h (hunk 2 above)
Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: @vryy I see, then maybe we can just use:

```C++ 
typedef double ** const ArrayType;
```

This should be equivalent to const pointer to a array of doubles (not sure if the `const` goes there or after `double`). This way you even may use the same function in the base class without having to derive and implement a different one for every case.

**Comment by roigcarlo** [comment]
My tests were with GCC 6.2 and Clang 3.9.

File: kratos/spatial_containers/bounding_volume_tree.h (hunk 2 above)
Comment (vryy) [reply kratos/spatial_containers/bounding_volume_tree.h]: I just made a pull request. Can someone review this?

**Comment by pooyan-dadvand** [comment]
@roigcarlo I think that @maceligueta is referring to the coefficient in the conflict of tetrahedra3d4.  For me the correct one is 6. @roigcarlo would you please confirm it?

**Comment by roigcarlo** [comment]
Oh, I see, sorry, too many too similar numbers. The correct one is 6.

**Edit:** From here 0f2c07f06d056cc6d84609478a8759950c368d8e

File: kratos/spatial_containers/bounding_volume_tree.h (hunk 2 above)
Comment (maceligueta) [reply kratos/spatial_containers/bounding_volume_tree.h]: can you reference the PR? I can't find it...

Comment (roigcarlo) [reply kratos/spatial_containers/bounding_volume_tree.h]: Here #143

**Comment by maceligueta** [comment]
I merged master into this branch and resolved the conficts. I think we are ready to merge this @roigcarlo , @pooyan-dadvand,  @RiccardoRossi ?

**Comment by pooyan-dadvand** [comment]
For some reason the diffs are not working well... BTW I trust in @maceligueta changes 👍

**Comment by RiccardoRossi** [comment]
+1 for the changes

**Comment by roigcarlo** [comment]
:+1: for me too
